#!/usr/bin/env ruby

require 'time'
require './lib/mysql_connection'
require './lib/subject'

CaptureTimeThreshold = 60

Subjects = []

Errors = []

def walk_season(root)
  # Directory structure is {root}/{site}/{roll}/{image}

  root_path = File.expand_path root
  total = Dir[File.join root_path, '**/*.{jpg,JPG,jpeg,JPEG}'].count
  index = 0.0

  Dir.new(root_path).each do |site|
    next if site.start_with? '.'

    site_path = File.expand_path File.join root, site
    Dir.new(site_path).each do |roll|
      next if roll.start_with? '.'

      roll_path = File.expand_path File.join root, site, roll
      Dir.new(roll_path).each do |image|
        next if image.match(/jpg$/i).nil?

        index = index + 1
        done = "#{(index / total) * 100}%"
        puts done

        image_path = File.expand_path File.join root, site, roll, image

        query = "SELECT * FROM `image` WHERE `Filename` = '#{image}' AND `SiteCode` = '#{site}' AND `SiteRollCode` LIKE '%#{roll}'"
        matches = Mysql.query(query).to_a

        if matches.count != 1
          puts "#{matches.count} found for #{site}/#{roll}/#{image}!"
          Errors << matches
        else
          last_subject = Subjects.last
          match = matches.first

          if last_subject
            difference = last_subject.location.keys.last - match['DateTime']
          end

          if last_subject.nil? or difference.abs > CaptureTimeThreshold
            unless last_subject.nil?
              puts last_subject.location
              puts last_subject.coords.join ', '
            end

            Subjects << Subject.new(match, roll, site)
          else
            last_subject.location.merge!({match['DateTime'] => match['Filename']})
          end
        end
      end
    end
  end
end

walk_season ARGV[0]
